main:
  - name: Home
    url:
    weight: 1
  - name: Pricing
    url: /#pricing
    weight: 2
  - name: Contact
    url: contact/
    weight: 3
footer_01:
  - name: Contact us
    url: contact/
    weight: 1
  - name: Pricing
    url: /#pricing
    weight: 2
footer_02:
#  - name: Blog
#    url: blog/
#    weight: 1
  - name: Terms & Conditions
    url: terms-conditions/
    weight: 1
