main:
  - name: Home
    url:
    weight: 1
  - name: About
    url: about/
    weight: 2
  - name: Pricing
    url: pricing/
    weight: 3
  - name: Contact
    url: contact/
    weight: 4
footer_01:
  - name: About us
    url: about/
    weight: 1
  - name: Contact us
    url: contact/
    weight: 2
  - name: Pricing
    url: pricing/
    weight: 3
footer_02:
  - name: Blog
    url: blog/
    weight: 1
  - name: Career
    url: career/
    weight: 2
  - name: Terms & Conditions
    url: terms-conditions/
    weight: 3
